apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-dev
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/jcepedav/keycloak-app.git
    targetRevision: main
    path: keycloak-app/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-prod
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/jcepedav/keycloak-app.git
    targetRevision: main
    path: keycloak-app/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
