apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rhbk-db-secret-secret.yaml
  - postgresql-statefulset.yaml
  - keycloak-cert-manager-certificate.yaml
  - rhbk-demo-keycloak.yaml

# Configuraci√≥n de variables
replacements:
  - source:
      kind: ConfigMap
      name: keycloak-config
      fieldPath: data.hostname
    targets:
      - select:
          kind: Keycloak
          name: rhbk-demo
        fieldPaths:
          - spec.hostname.hostname
      - select:
          kind: Certificate
          name: rhbk-demo-cert
        fieldPaths:
          - spec.commonName
          - spec.dnsNames.0

configMapGenerator:
  - name: keycloak-config
    literals:
      - hostname=rhbk-demo-rhbk.apps.cluster-858h6.858h6.sandbox2642.opentlc.com
