---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operators
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/jcepedav/keycloak-app
    targetRevision: HEAD
    path: ./keycloak-helm/operators
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/jcepedav/keycloak-app
    targetRevision: HEAD
    path: ./keycloak-helm/keycloak
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # This app depends on operators being installed first
  info:
    - name: Dependencies
      value: Requires keycloak-operators to be synced first
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-observability
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/jcepedav/keycloak-app
    targetRevision: HEAD
    path: ./keycloak-helm/observability
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # This app depends on keycloak-app being deployed
  info:
    - name: Dependencies
      value: Requires keycloak-app to be deployed first
