apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: keycloak-prod

patches:
  - target:
      kind: Secret
      name: rhbk-demo-db-secret
    patch: |-
      - op: replace
        path: /stringData/POSTGRES_EXTERNAL_ADDRESS
        value: postgresql.keycloak-prod.svc.cluster.local

replacements:
  - source:
      kind: Namespace
      fieldPath: metadata.name
    targets:
      - select:
          kind: Namespace
        fieldPaths:
          - metadata.name
        options:
          create: true
      - select:
          kind: OperatorGroup
        fieldPaths:
          - metadata.namespace
          - spec.targetNamespaces.0
      - select:
          kind: Subscription
        fieldPaths:
          - metadata.namespace
