apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rhsso-operator.yaml
  - rhbk-db-secret-secret.yaml
  - postgresql-statefulset.yaml
  - keycloak-cert-manager-certificate.yaml
  - rhbk-demo-keycloak.yaml
